---
- name: Deploy React project
  hosts: all
  become: yes
  vars:
    local_build_path: "./build"
    remote_path: "/var/www/html"
    
  tasks:
    - name: Install Node.js and npm
      package:
        name: 
          - nodejs
          - npm
        state: present
      delegate_to: localhost
      run_once: true

    - name: Install project dependencies
      npm:
        path: "{{ playbook_dir }}"
      delegate_to: localhost
      run_once: true

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ playbook_dir }}"
      delegate_to: localhost
      run_once: true

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes