---
- name: Deploy React project - Git Clone Only
  hosts: all
  become: yes
  vars:
    github_repo: "git@github.com:ZhisongZhang/gpsnet_report_projects.git"
    remote_repo_path: "/projects/react"
  
  tasks:
    - name: git clone the repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ remote_repo_path }}"
        version: "main"
        force: yes
      
    