---
- name: Deploy React project - Git Clone Only
  hosts: all
  become: yes
  vars:
    github_repo: "git@github.com:ZhisongZhang/gpsnet_report_projects.git"
    remote_repo_path: "/projects/react"
  
  tasks:
    - name: Install Git
      package:
        name: git
        state: present
      
    - name: Ensure project directory exists
      file:
        path: "{{ remote_repo_path }}"
        state: directory
        mode: '0755'
        
    - name: Clone the repository to the remote server
      git:
        repo: "{{ github_repo }}"
        dest: "{{ remote_repo_path }}/gpsnet_report_projects"
        clone: yes
        update: yes
        accept_hostkey: yes
      
    