---
- name: Deploy React project
  hosts: all
  become: yes
  vars:
    # Assuming the repository is already cloned by Semaphore
    project_path: "{{ playbook_dir }}/../gpsnet_report_projects"  # Path relative to playbook directory
    frontend_path: "{{ playbook_dir }}/../gpsnet_report_projects/gpsnet_file_completeness/gpsnet_file_completeness_frontend"
    local_build_path: "{{ playbook_dir }}/../gpsnet_report_projects/gpsnet_file_completeness/gpsnet_file_completeness_frontend/build"
    remote_path: "/var/www/html"
  
  pre_tasks:
    - name: Gather facts about localhost
      setup:
      delegate_to: localhost
      delegate_facts: true
      run_once: true
      become: no
      
  tasks:
    - name: Check if Node.js is already installed
      shell: command -v node || echo "not found"
      delegate_to: localhost
      run_once: true
      become: no
      register: node_exists
      ignore_errors: yes
      
    - name: Check if npm is already installed
      shell: command -v npm || echo "not found"
      delegate_to: localhost
      run_once: true
      become: no
      register: npm_exists
      ignore_errors: yes
      
    - name: Show Node.js and npm status
      debug:
        msg: 
          - "Node.js status: {{ 'Found' if 'not found' not in node_exists.stdout else 'Not found' }}"
          - "npm status: {{ 'Found' if 'not found' not in npm_exists.stdout else 'Not found' }}"
      
    # Skip Node.js installation tasks if they are already installed
    - name: Skip Node.js installation note
      debug:
        msg: "Node.js and npm appear to be already installed. Skipping installation."
      when: "'not found' not in node_exists.stdout and 'not found' not in npm_exists.stdout"
      
    - name: Install project dependencies
      npm:
        path: "{{ frontend_path }}"
        state: present
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Install project dependencies
      npm:
        path: "{{ frontend_path }}"
        state: present
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Install project dependencies
      npm:
        path: "{{ frontend_path }}"
        state: present
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Install project dependencies
      npm:
        path: "{{ frontend_path }}"
        state: present
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Install project dependencies
      npm:
        path: "{{ frontend_path }}"
        state: present
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Build React project
      command: npm run build
      args:
        chdir: "{{ frontend_path }}"
      delegate_to: localhost
      run_once: true
      become: no
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Create remote directory
      file:
        path: "{{ remote_path }}"
        state: directory
        mode: '0755'

    - name: Transfer build files to remote host
      synchronize:
        src: "{{ local_build_path }}/"
        dest: "{{ remote_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost

    - name: Set proper permissions
      file:
        path: "{{ remote_path }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes